export const STATIC_BETA_ASSETS = Object.freeze([
  ['leynor-brand.js', 'text/javascript; charset=utf-8'],
  ['leynor-logo.js', 'text/javascript; charset=utf-8'],
  ['leynor-brand.css', 'text/css; charset=utf-8'],
  ['pwa.js', 'text/javascript; charset=utf-8'],
  ['pwa.css', 'text/css; charset=utf-8'],
  ['manifest.webmanifest', 'application/manifest+json; charset=utf-8'],
  ['service-worker.js', 'text/javascript; charset=utf-8'],
  ['api-fetch-router.js', 'text/javascript; charset=utf-8'],
  ['api-connection.js', 'text/javascript; charset=utf-8'],
  ['leynor-assistant.js', 'text/javascript; charset=utf-8'],
  ['leynor-conversation.js', 'text/javascript; charset=utf-8'],
  ['leynor-financial-cards.js', 'text/javascript; charset=utf-8'],
  ['browser-voice.js', 'text/javascript; charset=utf-8'],
  ['guided-tour.js', 'text/javascript; charset=utf-8'],
  ['guided-tour.css', 'text/css; charset=utf-8'],
  ['opportunity-radar-ui.js', 'text/javascript; charset=utf-8'],
  ['leynor-lab.html', 'text/html; charset=utf-8'],
  ['leynor-lab-ui.js', 'text/javascript; charset=utf-8'],
  ['leynor-premium-lab.js', 'text/javascript; charset=utf-8'],
  ['leynor-premium-lab-advanced.js', 'text/javascript; charset=utf-8'],
  ['leynor-lab-regimes.js', 'text/javascript; charset=utf-8'],
  ['mobile-ui.js', 'text/javascript; charset=utf-8'],
  ['storage-schema.js', 'text/javascript; charset=utf-8'],
  ['storage-bootstrap.js', 'text/javascript; charset=utf-8'],
  ['boot-diagnostics.js', 'text/javascript; charset=utf-8'],
  ['interaction-audit.js', 'text/javascript; charset=utf-8'],
  ['diagnostics-panel.js', 'text/javascript; charset=utf-8'],
  ['diagnostics-panel.css', 'text/css; charset=utf-8'],
  ['icons/leynor-icon.svg', 'image/svg+xml'],
  ['icons/leynor-maskable.svg', 'image/svg+xml']
]);
