import { createHash } from 'node:crypto';
import { validationSummary, compareToBenchmark } from '../modeling/probability-validation.js';

function probability(value, field) { const number=Number(value); if(!Number.isFinite(number)||number<0||number>1)throw new TypeError(`${field} doit être compris entre 0 et 1.`); return number; }
function iso(value, field) { if(typeof value!=='string'||Number.isNaN(Date.parse(value)))throw new TypeError(`${field} doit être une date ISO.`); return value; }
function wilson(successes, total, z=1.959963984540054) { if(!total)return null; const p=successes/total,den=1+z*z/total,center=(p+z*z/(2*total))/den,margin=z*Math.sqrt(p*(1-p)/total+z*z/(4*total*total))/den; return Object.freeze({lower:Math.max(0,center-margin),upper:Math.min(1,center+margin)}); }
export function evaluateIntervalCoverage(records, levels=[0.5,0.9]) { return Object.freeze(levels.map(level=>{probability(level,'level');const eligible=records.filter(r=>Number.isFinite(r.intervals?.[String(level)]?.lower)&&Number.isFinite(r.intervals?.[String(level)]?.upper)&&Number.isFinite(r.outcome));const hits=eligible.filter(r=>r.outcome>=r.intervals[String(level)].lower&&r.outcome<=r.intervals[String(level)].upper).length;const rate=eligible.length?hits/eligible.length:null;const ci=wilson(hits,eligible.length);return Object.freeze({level,sampleSize:eligible.length,hits,observedCoverage:rate,wilson95:ci,compatible:ci?ci.lower<=level&&ci.upper>=level:false});})); }
export function evaluateProbabilityCalibration(records, benchmarkProbability) { const pairs=records.map(r=>({probability:r.probability,outcome:r.binaryOutcome})); const model=validationSummary(pairs); const benchmark=validationSummary(records.map(r=>({probability:benchmarkProbability,outcome:r.binaryOutcome}))); return Object.freeze({model,benchmark,comparison:compareToBenchmark(model,benchmark)}); }
function fingerprint(value){return createHash('sha256').update(JSON.stringify(value)).digest('hex');}
export function createProspectiveForecast(input){const payload={schemaVersion:1,forecastId:String(input.forecastId||'').trim(),engineCommit:String(input.engineCommit||'').trim(),portfolioId:String(input.portfolioId||'').trim(),asOf:iso(input.asOf,'asOf'),maturesAt:iso(input.maturesAt,'maturesAt'),horizonMonths:Number(input.horizonMonths),probability:probability(input.probability,'probability'),intervals:input.intervals,assumptionsFingerprint:String(input.assumptionsFingerprint||'').trim(),createdWithoutOutcomeAccess:input.createdWithoutOutcomeAccess===true};if(!payload.forecastId||!payload.engineCommit||!payload.portfolioId||!payload.assumptionsFingerprint)throw new TypeError('identifiants et empreintes requis.');if(!Number.isInteger(payload.horizonMonths)||payload.horizonMonths<1)throw new TypeError('horizonMonths invalide.');if(Date.parse(payload.maturesAt)<=Date.parse(payload.asOf))throw new TypeError('maturesAt doit être postérieur à asOf.');if(!payload.createdWithoutOutcomeAccess)throw new TypeError('createdWithoutOutcomeAccess doit être true.');return Object.freeze({...payload,fingerprint:fingerprint(payload)});}
export function settleProspectiveForecast(forecast,{observedAt,outcome,binaryOutcome},now=new Date().toISOString()){if(Date.parse(now)<Date.parse(forecast.maturesAt))throw new Error('prévision non mature : lecture du résultat interdite.');const normalized={forecastFingerprint:forecast.fingerprint,observedAt:iso(observedAt,'observedAt'),outcome:Number(outcome),binaryOutcome:Boolean(binaryOutcome)};if(!Number.isFinite(normalized.outcome))throw new TypeError('outcome doit être fini.');if(Date.parse(normalized.observedAt)<Date.parse(forecast.maturesAt))throw new Error('observedAt antérieur à la maturité.');return Object.freeze({...normalized,fingerprint:fingerprint(normalized)});}
